// Code generated by protoc-gen-go. DO NOT EDIT.
// source: networkspeed.proto

package networkspeed

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	LastCheck            int64       `protobuf:"varint,1,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	Transfers            []*Transfer `protobuf:"bytes,2,rep,name=transfers,proto3" json:"transfers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb4429519ee6ee7, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLastCheck() int64 {
	if m != nil {
		return m.LastCheck
	}
	return 0
}

func (m *Config) GetTransfers() []*Transfer {
	if m != nil {
		return m.Transfers
	}
	return nil
}

type Transfer struct {
	MessageSize          int64    `protobuf:"varint,1,opt,name=message_size,json=messageSize,proto3" json:"message_size,omitempty"`
	Origin               string   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb4429519ee6ee7, []int{1}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetMessageSize() int64 {
	if m != nil {
		return m.MessageSize
	}
	return 0
}

func (m *Transfer) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Transfer) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type TransferRequest struct {
	ByteSize             int64    `protobuf:"varint,1,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb4429519ee6ee7, []int{2}
}

func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (m *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(m, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetByteSize() int64 {
	if m != nil {
		return m.ByteSize
	}
	return 0
}

func (m *TransferRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type TransferResponse struct {
	ProcessingTime       int64    `protobuf:"varint,1,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferResponse) Reset()         { *m = TransferResponse{} }
func (m *TransferResponse) String() string { return proto.CompactTextString(m) }
func (*TransferResponse) ProtoMessage()    {}
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb4429519ee6ee7, []int{3}
}

func (m *TransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferResponse.Unmarshal(m, b)
}
func (m *TransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferResponse.Marshal(b, m, deterministic)
}
func (m *TransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferResponse.Merge(m, src)
}
func (m *TransferResponse) XXX_Size() int {
	return xxx_messageInfo_TransferResponse.Size(m)
}
func (m *TransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransferResponse proto.InternalMessageInfo

func (m *TransferResponse) GetProcessingTime() int64 {
	if m != nil {
		return m.ProcessingTime
	}
	return 0
}

type RecordRequest struct {
	Transfer             *Transfer `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecordRequest) Reset()         { *m = RecordRequest{} }
func (m *RecordRequest) String() string { return proto.CompactTextString(m) }
func (*RecordRequest) ProtoMessage()    {}
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb4429519ee6ee7, []int{4}
}

func (m *RecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordRequest.Unmarshal(m, b)
}
func (m *RecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordRequest.Marshal(b, m, deterministic)
}
func (m *RecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordRequest.Merge(m, src)
}
func (m *RecordRequest) XXX_Size() int {
	return xxx_messageInfo_RecordRequest.Size(m)
}
func (m *RecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecordRequest proto.InternalMessageInfo

func (m *RecordRequest) GetTransfer() *Transfer {
	if m != nil {
		return m.Transfer
	}
	return nil
}

type RecordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordResponse) Reset()         { *m = RecordResponse{} }
func (m *RecordResponse) String() string { return proto.CompactTextString(m) }
func (*RecordResponse) ProtoMessage()    {}
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb4429519ee6ee7, []int{5}
}

func (m *RecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordResponse.Unmarshal(m, b)
}
func (m *RecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordResponse.Marshal(b, m, deterministic)
}
func (m *RecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordResponse.Merge(m, src)
}
func (m *RecordResponse) XXX_Size() int {
	return xxx_messageInfo_RecordResponse.Size(m)
}
func (m *RecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Config)(nil), "networkspeed.Config")
	proto.RegisterType((*Transfer)(nil), "networkspeed.Transfer")
	proto.RegisterType((*TransferRequest)(nil), "networkspeed.TransferRequest")
	proto.RegisterType((*TransferResponse)(nil), "networkspeed.TransferResponse")
	proto.RegisterType((*RecordRequest)(nil), "networkspeed.RecordRequest")
	proto.RegisterType((*RecordResponse)(nil), "networkspeed.RecordResponse")
}

func init() { proto.RegisterFile("networkspeed.proto", fileDescriptor_ccb4429519ee6ee7) }

var fileDescriptor_ccb4429519ee6ee7 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xb1, 0x6e, 0xea, 0x30,
	0x14, 0x86, 0x6f, 0x40, 0xe2, 0x92, 0x43, 0x0a, 0xc8, 0x03, 0x8a, 0xa0, 0x54, 0xa9, 0x97, 0x32,
	0x31, 0xd0, 0x6e, 0x1d, 0x59, 0xba, 0xa0, 0x4a, 0x81, 0xb5, 0x42, 0x26, 0x39, 0xa4, 0x16, 0x60,
	0xa7, 0xb6, 0xdb, 0x0a, 0xde, 0xaa, 0x6f, 0x58, 0x11, 0xe2, 0x84, 0x48, 0xcd, 0xe8, 0xef, 0xb7,
	0xff, 0xcf, 0x3e, 0x32, 0x10, 0x81, 0xe6, 0x5b, 0xaa, 0x9d, 0x4e, 0x11, 0xe3, 0x69, 0xaa, 0xa4,
	0x91, 0xc4, 0xbb, 0x66, 0xf4, 0x0d, 0x5a, 0x73, 0x29, 0xb6, 0x3c, 0x21, 0x63, 0x80, 0x3d, 0xd3,
	0x66, 0x1d, 0xbd, 0x63, 0xb4, 0xf3, 0x9d, 0xc0, 0x99, 0x34, 0x43, 0xf7, 0x4c, 0xe6, 0x67, 0x40,
	0x9e, 0xc0, 0x35, 0x8a, 0x09, 0xbd, 0x45, 0xa5, 0xfd, 0x46, 0xd0, 0x9c, 0x74, 0x66, 0x83, 0x69,
	0xa5, 0x7e, 0x95, 0xc7, 0x61, 0xb9, 0x91, 0x26, 0xd0, 0xb6, 0x98, 0xdc, 0x83, 0x77, 0x40, 0xad,
	0x59, 0x82, 0x6b, 0xcd, 0x4f, 0x98, 0x2b, 0x3a, 0x39, 0x5b, 0xf2, 0x13, 0x92, 0x01, 0xb4, 0xa4,
	0xe2, 0x09, 0x17, 0x7e, 0x23, 0x70, 0x26, 0x6e, 0x98, 0xaf, 0x48, 0x00, 0x9d, 0x18, 0xb5, 0xe1,
	0x82, 0x19, 0x2e, 0x85, 0xdf, 0xcc, 0xc2, 0x6b, 0x44, 0x5f, 0xa0, 0x57, 0xf8, 0xf1, 0xe3, 0x13,
	0xb5, 0x21, 0x23, 0x70, 0x37, 0x47, 0x53, 0x91, 0xb5, 0xcf, 0x20, 0x33, 0xf9, 0xf0, 0x3f, 0x65,
	0xc7, 0xbd, 0x64, 0x71, 0xa6, 0xf2, 0x42, 0xbb, 0xa4, 0xcf, 0xd0, 0x2f, 0x9b, 0x74, 0x2a, 0x85,
	0x46, 0xf2, 0x00, 0xbd, 0x54, 0xc9, 0x08, 0xb5, 0xe6, 0x22, 0x59, 0x1b, 0x7e, 0xb0, 0x85, 0xdd,
	0x12, 0xaf, 0xf8, 0x01, 0xe9, 0x1c, 0x6e, 0x42, 0x8c, 0xa4, 0x8a, 0xed, 0x25, 0x66, 0xd0, 0xb6,
	0xd3, 0xc8, 0x8e, 0xd4, 0x4f, 0xad, 0xd8, 0x47, 0xfb, 0xd0, 0xb5, 0x25, 0x17, 0xff, 0xec, 0xc7,
	0x29, 0x9f, 0xb7, 0x44, 0xf5, 0xc5, 0x23, 0x24, 0xaf, 0xe0, 0x2d, 0xd8, 0x0e, 0x8b, 0xf1, 0x8e,
	0x6b, 0x7a, 0x2f, 0x17, 0x19, 0xde, 0xd5, 0xc5, 0x17, 0x05, 0xfd, 0x47, 0x16, 0x56, 0x5b, 0x54,
	0x8e, 0xaa, 0x67, 0x2a, 0x2f, 0x1b, 0xde, 0xfe, 0x1d, 0xda, 0xba, 0x4d, 0x2b, 0xfb, 0x6e, 0x8f,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x99, 0x33, 0xcd, 0x84, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransferServiceClient interface {
	MakeTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	RecordTransfer(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
}

type transferServiceClient struct {
	cc *grpc.ClientConn
}

func NewTransferServiceClient(cc *grpc.ClientConn) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) MakeTransfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, "/networkspeed.TransferService/MakeTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) RecordTransfer(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, "/networkspeed.TransferService/RecordTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferServiceServer is the server API for TransferService service.
type TransferServiceServer interface {
	MakeTransfer(context.Context, *TransferRequest) (*TransferResponse, error)
	RecordTransfer(context.Context, *RecordRequest) (*RecordResponse, error)
}

func RegisterTransferServiceServer(s *grpc.Server, srv TransferServiceServer) {
	s.RegisterService(&_TransferService_serviceDesc, srv)
}

func _TransferService_MakeTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).MakeTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkspeed.TransferService/MakeTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).MakeTransfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_RecordTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).RecordTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/networkspeed.TransferService/RecordTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).RecordTransfer(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransferService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "networkspeed.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeTransfer",
			Handler:    _TransferService_MakeTransfer_Handler,
		},
		{
			MethodName: "RecordTransfer",
			Handler:    _TransferService_RecordTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "networkspeed.proto",
}
