// Code generated by protoc-gen-go. DO NOT EDIT.
// source: networkspeed.proto

package networkspeed

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	LastCheck            int64       `protobuf:"varint,1,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	Transfers            []*Transfer `protobuf:"bytes,2,rep,name=transfers,proto3" json:"transfers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb4429519ee6ee7, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLastCheck() int64 {
	if m != nil {
		return m.LastCheck
	}
	return 0
}

func (m *Config) GetTransfers() []*Transfer {
	if m != nil {
		return m.Transfers
	}
	return nil
}

type Transfer struct {
	MessageSize          int64    `protobuf:"varint,1,opt,name=message_size,json=messageSize,proto3" json:"message_size,omitempty"`
	Origin               string   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb4429519ee6ee7, []int{1}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetMessageSize() int64 {
	if m != nil {
		return m.MessageSize
	}
	return 0
}

func (m *Transfer) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Transfer) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "networkspeed.Config")
	proto.RegisterType((*Transfer)(nil), "networkspeed.Transfer")
}

func init() { proto.RegisterFile("networkspeed.proto", fileDescriptor_ccb4429519ee6ee7) }

var fileDescriptor_ccb4429519ee6ee7 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcf, 0xc1, 0x8a, 0x83, 0x30,
	0x10, 0x06, 0x60, 0x54, 0x90, 0x75, 0xf4, 0x94, 0x83, 0xe4, 0xb2, 0x90, 0xf5, 0xe4, 0xc9, 0xc3,
	0xee, 0xbe, 0x81, 0x6f, 0xe0, 0xee, 0xb5, 0x48, 0xaa, 0x63, 0x1a, 0x6c, 0x13, 0xc9, 0x04, 0x0a,
	0x3e, 0x7d, 0x51, 0x52, 0x6a, 0x8f, 0xf3, 0xfd, 0xc3, 0x0c, 0x3f, 0x30, 0x83, 0xfe, 0x6e, 0xdd,
	0x4c, 0x0b, 0xe2, 0xd8, 0x2c, 0xce, 0x7a, 0xcb, 0x8a, 0xa3, 0x55, 0x27, 0x48, 0x5b, 0x6b, 0x26,
	0xad, 0xd8, 0x27, 0xc0, 0x55, 0x92, 0xef, 0x87, 0x0b, 0x0e, 0x33, 0x8f, 0x44, 0x54, 0x27, 0x5d,
	0xb6, 0x49, 0xbb, 0x01, 0xfb, 0x85, 0xcc, 0x3b, 0x69, 0x68, 0x42, 0x47, 0x3c, 0x16, 0x49, 0x9d,
	0x7f, 0x97, 0xcd, 0xdb, 0xf9, 0xff, 0x10, 0x77, 0xaf, 0xc5, 0x4a, 0xc1, 0xc7, 0x93, 0xd9, 0x17,
	0x14, 0x37, 0x24, 0x92, 0x0a, 0x7b, 0xd2, 0x2b, 0x86, 0x17, 0x79, 0xb0, 0x3f, 0xbd, 0x22, 0x2b,
	0x21, 0xb5, 0x4e, 0x2b, 0x6d, 0x78, 0x2c, 0xa2, 0x3a, 0xeb, 0xc2, 0xc4, 0x04, 0xe4, 0x23, 0x92,
	0xd7, 0x46, 0x7a, 0x6d, 0x0d, 0x4f, 0xf6, 0xf0, 0x48, 0xe7, 0x74, 0x2f, 0xf7, 0xf3, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x06, 0x31, 0x9c, 0x12, 0xf2, 0x00, 0x00, 0x00,
}
